date = "today"

[todos.x]
name = "x"
notes = "x"
complete = true

[todos."something new"]
name = "something new"
notes = "yes"
complete = false

[todos."finish adding postges to daylist"]
name = "Finish adding Postges to Daylist"
notes = "Currently creating a new migration"
complete = false
